### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fairOS-dfs#156]
Add configuration file that is read on start:
- CORS settings
- postage stamp Id 

any other ideas ?

**Comment by asabya** [comment]
adding these for now
```
bee:
  bee-api-endpoint: 127.0.0.1:1633
  bee-debug-api-endpoint: 127.0.0.1:1635
  postage-batch-id: someId
cookie-domain: localhost
cors-allowed-origins: [localhost:8080]
dfs:
  config: /home/User/.dfs.yaml
  data-dir: /home/User/.fairOs/dfs
  ports:
    http-port: :9090
    pprof-port: :9091
verbosity: info
```
